<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ThinkControl.Core\ThinkControl.Core.csproj" />
    <ProjectReference Include="..\ThinkControl.DeviceProfiles\ThinkControl.DeviceProfiles.csproj" />
    <ProjectReference Include="..\ThinkControl.Hardware\ThinkControl.Hardware.csproj" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.2" />
  </ItemGroup>
</Project>
