<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\trackpoint.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ThinkControl.Core\ThinkControl.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks.Lucide" Version="6.2.1" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.Management" Version="10.0.0" />
  </ItemGroup>
</Project>
